### ISSUE TITLE
20 Questions

### ISSUE THREAD

**Issue by mses-bly** [z-ct/autonomous#11]
20 Questions (top 20 questions about your company/concerns, etc.) What are the top 20 questions that investors, users, etc. will ask you about your company.

**Comment by gpekar** [comment]
https://github.com/z-ct/autonomous/blob/master/artifacts/startup_studio/20q.md

**Comment by oatsandsugar** [comment]
to be reviewed

**Comment by pablowatfi** [comment]
I don't know if we submitted already, but it just occurred to me that an investor will probably ask about competition. Who are we competing with?

**Comment by oatsandsugar** [comment]
Put it into the list! I agree :)
