### ISSUE TITLE
Investment homework

### ISSUE THREAD

**Issue by mses-bly** [z-ct/autonomous#13]
- [x] @oatsandsugar
- [x] @mses-bly 
- [x] @pablowatfi 
- [x] @gpekar

**Comment by mses-bly** [comment]
https://docs.google.com/spreadsheets/d/1cBiZH8efq6DdHRY-ErI38FRjVvPraRCeE4WyrrGg99M/edit#gid=406612753

In the first and second tabs

**Comment by oatsandsugar** [comment]
I went for:
Johanan Ottensooser	SageLink	60k	| Datalogue	30k |	Team Alice	10k

**Comment by gpekar** [comment]
two.one	50k	
Charlie's Angels	20k	
Doorway Technologies	30k

**Comment by mses-bly** [comment]
I like SageLink a lot (although is gonna be hard to come up with a non-invasive approach). Then Zaid's idea for vehicle signals is very interesting from an autopilot/self-driving car (like in planes, if there is an issue, you got to be woken up). And then the inmates payment platform is just fucking brilliant...

**Comment by pablowatfi** [comment]
I went with Datalogue 35k, TwoPlusTwo 2.1 35k and two.one 30k
