### ISSUE TITLE
Complete the initial version of your Dashboard

### ISSUE THREAD

**Issue by mses-bly** [z-ct/autonomous#16]
- [x] agree on metrics
- [x] design actual dashboard

**Comment by oatsandsugar** [comment]
For review / addition, please do ASAP as I will start mocking up the dashboard this afternoon.

https://github.com/z-ct/autonomous/blob/master/artifacts/product_management/dashboard_contents.md

**Comment by mses-bly** [comment]
Three tabs - trust, health and finance.

Volume of transactions.
Devices on network.
Avg budget detection.

% transactions disputed
Perception of fairnessThree tabs - trust, health and finance.


bids / transaction
vendor / seller mix

**Comment by oatsandsugar** [comment]
https://github.com/z-ct/autonomous/blob/master/artifacts/product_management/dashboard_contents.md
