### ISSUE TITLE
Choose some of your favorite apps and make sure they are downloaded on your device for next class

### ISSUE THREAD

**Issue by mses-bly** [z-ct/autonomous#17]
Print out three screenshots you want to discuss/critique and bring them to class

**Comment by oatsandsugar** [comment]
ideas:
- [ ] unicornicopia
- [ ] MyFitnessPal
- [ ] Swarm
- [ ] Overcast
- [ ] Citymapper
- [ ] NYT

**Comment by mses-bly** [comment]
ideas:
- [ ] Square Cash
- [ ] Venmo
- [ ] GMaps
- [ ] ExpenseIQ

**Comment by mses-bly** [comment]
Close this after class
