### ISSUE TITLE
Add your product narrative to the homework doc.

### ISSUE THREAD

**Issue by mses-bly** [z-ct/autonomous#4]
Studio Links: https://confluence.cornell.edu/pages/viewpage.action?spaceKey=studio&title=Studio+Links+and+Info

**Comment by mses-bly** [comment]
Narrative:
https://github.com/z-ct/autonomous/blob/master/narrative.md

**Comment by oatsandsugar** [comment]
reviewed ✔️ 

Beginning could still use a bit of work, but it is a good start
