### ISSUE TITLE
Create the initial version of your System Diagram & Wedge

### ISSUE THREAD

**Issue by mses-bly** [z-ct/autonomous#8]

**Comment by mses-bly** [comment]
https://github.com/z-ct/autonomous/blob/master/artifacts/product_management/system_diagram.png

Being a lousy designer, this is what I did with my free time. Tear it apart.
Editable google drawing:

https://docs.google.com/a/cornell.edu/drawings/d/14QxWfjRI1yoDpjX0tFHoJci6YKrZLfArsqq66tVGdMw/edit?usp=sharing

Added to artifacts

**Comment by oatsandsugar** [comment]
summary of comments from slack:

- [ ] (1) we *must* add a wedge before tomorrow
- [ ] (2) we should consider making an agnostic system diagram, including vendors, payment providers and sellers

**Comment by mses-bly** [comment]
`• [ ] (2) we should consider making an agnostic system diagram, including vendors, payment providers and sellers`
in a car to car bribe system who is the vendor or seller?
essentially, depending on the application, it is not as clear cut (from the architecture perspective), to see as a centralized standard system with buyers, sellers and a comm channel in the middle. is more of a distributed peer to peer network that enforces the protocols. not sure what you mean by `agnostic`. like a box with two sides, buyers and sellers and our marketplace in the middle?
anyways, can you elaborate more? Maybe I'm overcomplicating.

(1) Sure, I'll add a triangle that says trust :sweat_smile:
